### ISSUE TITLE
OUTRAGOUS

### ISSUE THREAD

**Issue by Draco666** [Priveyes/burst-pool#3]
OMG i cannot believe someones forked lex's pool code. removed all credits, and his dev fee and removed all backwards comparability for his prior users.

im betting this is the same guy who tried to ruin lex's credibility in the forums calling him a copy and  paste coder. yet he copy and pasted lex's code.

you should be ashamed of yourself. lex is a respected member of the community and he  put in loads of work fixing the ghost block issue the original uray pool had huge issues with. and spent money out of his own pocket trying to fix them. 

also are you going to give the users remote support for these versions like lex did with his. cause we cant expect him to support a release he didnt write!.

**Comment by Pascal66** [comment]
It's a dev branch, not an usable one
